title:            Huals's Home
description:      "write my life"
logo:             omikron.png
disqus_shortname:  huals
duoshuo_shortname:  huals
# Assign a default image for your site's header and footer
default_bg:       http://huals.com/default_bg1.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Specify the average Words per minute. If not defined, 180 will be used
wpm:				      200
# Turn on or off the fin animations in the header and footer
triangleheader:		true
animated_fins:	  true
# Specify the fin color in RGB value
fin_color:        "255,255,255"
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:       		   http://huals.com

# Owner/author information
owner:
  name:           huals
  avatar:         huals.jpg
  email:          hualinsen@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    恍恍惚惚红红火火哈哈哈哈
  # Social networking links used in footer. Update and remove as you like.
  twitter:        LinsenHua
  facebook:       linsen.hua
  github:         hualinsen
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  weibo: 2830568547
  # For Google Authorship https://plus.google.com/authorship
google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-52116871-3
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: 主页
    url: /
    external: false
    icon: home
  - title: 类目
    url: /categories
    icon: bars
  - title: 标签
    url: /tags
    icon: tags
  - title: 留言板
    url: /guestbook
    icon: comments
  - title: 友情链接
    url: /links
    icon: link
  - title: 关于我
    url: /about
    icon: user

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
highlighter: pygments
markdown:    kramdown
excerpt_separator: "<!--more-->"
paginate:    6
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    sass_dir: _sass
    style: :compressed
